name: BatchFelt
options:
  bundleIdPrefix: com.shimondeitel.feltinglog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "3"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  BatchFelt:
    type: application
    platform: iOS
    sources:
      - path: BatchFelt
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.feltinglog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: BatchFelt/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  BatchFeltTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: BatchFeltTests
      - path: BatchFelt.storekit
    dependencies:
      - target: BatchFelt
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.feltinglog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  BatchFeltUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: BatchFeltUITests
    dependencies:
      - target: BatchFelt
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.feltinglog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  BatchFelt:
    build:
      targets:
        BatchFelt: all
        BatchFeltTests: [test]
        BatchFeltUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: BatchFelt.storekit
    test:
      config: Debug
      storeKitConfiguration: BatchFelt.storekit
      targets:
        - BatchFeltTests
        - BatchFeltUITests
    archive:
      config: Release
